version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: mego_post_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
     - mego_post_network
  redis:
    container_name: mego_post_redis
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./tmp/redis:/data
    networks:
      - mego_post_network

  mego_post:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego-post
    depends_on:
      - postgres
      - redis
    ports:
      - "${POST_SERVICE_SERVER_PORT}:${POST_SERVICE_SERVER_PORT}"
    networks:
      - mego_post_network

networks:
  mego_post_network:
    driver: bridge